stages:
    - deployapi

deploy_dev_api:
    stage: deployapi
    before_script:
      - cd api
    script:
        - echo "Deploying dev API server"
        - npm install
        - cp /repos/lbym-app/config/api-dev-config.config ./config.js
        - cp -R ./* /repos/lbym-app/api-dev/
    environment:
        name: dev
        url: dev.lbym.org
    only:
        - dev

deploy_production_api:
  stage: deployapi
  before_script:
    - cd api
  script:
      - echo "Deploying API server"
      - npm install
      - cp /repos/lbym-app/config/api-config.config ./config.js
      - cp -R ./* /repos/lbym-app/api/
  environment:
      name: production
      url: app.lbym.org
  only:
      - master


deploy_test_api:
  stage: deployapi
  before_script:
    - cd api
  script:
      - echo "Deploying Dynamo Test API server"
      - npm install
      - cp /repos/lbym-app/config/aws-config.config ./config.js
      - cp -R ./* /repos/lbym-app/api-dynamotest/
  environment:
      name: production
      url: dynamo.lbym.org
  only:
      - dynamodb
