stages:
    - build
    - deploy
build:
    stage: build
    before_script:
      - cd site
    environment:
      name: "dev"
    script:
        - echo "Building deploy package"
        - npm install
        - CI=false npm run build
        - echo "Build successful"
    artifacts:
      expire_in: 1 hour
      paths:
        - site/build
deploy_dev:
    stage: deploy
    before_script:
      - cd site
    script:
        - echo "Deploying dev to server"
        - cp -rv build/* /var/www/lbym-app/dev
        - echo "Deployed"
    environment:
        name: dev
        url: dev.lbym.org
    only:
        - dev