stages:
    - prep
    - build
    - deploy

prep: 
  stage: prep
  script:
    - cp /repos/lbym-app/config/dev.config ./site/config.js
  only:
    - dev

prep: 
  stage: prep
  script:
    - cp /repos/lbym-app/config/release.config ./site/config.js
  only:
    - release

prep: 
  stage: prep
  script:
    - cp /repos/lbym-app/config/production.config ./site/config.js
  only:
    - master
    
build:
    stage: build
    before_script:
      - cd site
    environment:
      name: "dev"
    script:
        - echo "Building deploy package"
        - npm install
        - CI=false npm run build
        - echo "Build successful"
    artifacts:
      expire_in: 1 hour
      paths:
        - site/build

deploy_dev:
    stage: deploy
    before_script:
      - cd site
    script:
        - echo "Deploying dev to server"
        - cp -rv build/* /var/www/lbym-app/dev
        - echo "Deployed"
    environment:
        name: dev
        url: dev.lbym.org
    only:
        - dev

deploy_production:
    stage: deploy
    before_script:
      - cd site
    script:
        - echo "Deploying production to server"
        - cp -rv build/* /var/www/lbym-app/beta
        - echo "Deployed"
    environment:
        name: production
        url: app.lbym.org
    only:
        - release

deploy_release:
    stage: deploy
    before_script:
      - cd site
    script:
        - echo "Deploying production to server"
        - cp -rv build/* /var/www/lbym-app/public
        - echo "Deployed"
    environment:
        name: production
        url: app.lbym.org
    only:
        - master