stages:
    - prep
    - deployapi

prep: 
  stage: prep
  script:
    - cp /repos/lbym-app/config/dev.config ./site/src/config.js
  only:
    - dev

prep: 
  stage: prep
  script:
    - cp /repos/lbym-app/config/release.config ./site/src/config.js
  only:
    - release

prep: 
  stage: prep
  script:
    - cp /repos/lbym-app/config/production.config ./site/src/config.js
  only:
    - master

deploy_dev_api:
    stage: deployapi
    before_script:
      - cd api
    script:
        - echo "Deploying dev API server"
        - npm install
        - cp -R ./* /repos/lbym-app/api/
    environment:
        name: dev
        url: dev.lbym.org
    only:
        - dev

deploy_production_api:
  stage: deployapi
  before_script:
    - cd api
  script:
      - echo "Deploying API server"
      - npm install
      - cp -R ./* /repos/lbym-app/api/
  environment:
      name: dev
      url: app.lbym.org
  only:
      - master
